#ifndef gamgee__gamgee__guard
#define gamgee__gamgee__guard

#include "exceptions.h"
#include "fastq.h"
#include "fastq_iterator.h"
#include "fastq_reader.h"
#include "interval.h"
#include "missing.h"
#include "reference_iterator.h"
#include "reference_map.h"
#include "zip.h"

#include "utils/file_utils.h"
#include "utils/genotype_utils.h"
#include "utils/hts_memory.h"
#include "utils/merged_vcf_lut.h"
#include "utils/short_value_optimized_storage.h"
#include "utils/utils.h"
#include "utils/variant_field_type.h"
#include "utils/variant_utils.h"

#include "sam/base_quals.h"
#include "sam/cigar.h"
#include "sam/indexed_sam_iterator.h"
#include "sam/indexed_sam_reader.h"
#include "sam/read_bases.h"
#include "sam/sam.h"
#include "sam/sam_builder.h"
#include "sam/sam_builder_data_field.h"
#include "sam/sam_header.h"
#include "sam/sam_iterator.h"
#include "sam/sam_pair_iterator.h"
#include "sam/sam_reader.h"
#include "sam/sam_tag.h"
#include "sam/sam_writer.h"

#include "variant/genotype.h"
#include "variant/indexed_variant_iterator.h"
#include "variant/indexed_variant_reader.h"
#include "variant/individual_field.h"
#include "variant/individual_field_iterator.h"
#include "variant/individual_field_value.h"
#include "variant/individual_field_value_iterator.h"
#include "variant/multiple_variant_iterator.h"
#include "variant/multiple_variant_reader.h"
#include "variant/reference_block_splitting_variant_iterator.h"
#include "variant/shared_field.h"
#include "variant/shared_field_iterator.h"
#include "variant/synced_variant_iterator.h"
#include "variant/synced_variant_reader.h"
#include "variant/variant.h"
#include "variant/variant_builder.h"
#include "variant/variant_builder_individual_field.h"
#include "variant/variant_builder_individual_region.h"
#include "variant/variant_builder_multi_sample_vector.h"
#include "variant/variant_builder_shared_region.h"
#include "variant/variant_filters.h"
#include "variant/variant_filters_iterator.h"
#include "variant/variant_header.h"
#include "variant/variant_header_builder.h"
#include "variant/variant_iterator.h"
#include "variant/variant_reader.h"
#include "variant/variant_writer.h"
#include "variant/variant_header_merger.h"

#endif  /* gamgee__gamgee__guard */
